CREATE DATABASE IF NOT EXISTS playlist;
USE playlist;

CREATE TABLE IF NOT EXISTS music (
    id INT AUTO_INCREMENT PRIMARY KEY,
    musicName VARCHAR(50) NOT NULL,
    singer VARCHAR(50) NOT NULL
);
